#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi
export EDITOR=vim
alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias gco="git checkout"
source ~/.gvm/bin/gvm-init.sh
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"
unset NODE_PATH
export alias gco="git checkout"
alias LS="LS -alFe"
alias sl="sl -alFe"
export GOPATH=$HOME/gocode
autoload -U +X compinit && compinit
autoload -U +X bashcompinit && bashcompinit
alias stripwhitespace="find . -name $1 -type f -exec sed -i -e's/[[:space:]]*$//' $2 {} \;"
ppid() { ps -p ${1:-$$} -o ppid=; }
randpw() { dd if=/dev/urandom bs=1 count=$1 2>/dev/null | base64 -w 0 | rev | cut -b 2- | rev }
gpr() { git fetch $1 pull/$2/head:$3 }

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"
